services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: second_brain_app  
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    volumes:
      - ../db:/app/db
